version: '3.4'

services:

   api:
     build:
       context: .
       network: host
     container_name: dbrshop-svc
     image: dbrshop-svc:latest
     volumes:
       - .:/go/src/dbrshop-svc
       - ..:/go/src
     command: fresh
    #  command: go version
     ports:
       - "8081:8081"
       - "10443:10443"
     restart: always